"""add size color and quality to products

Revision ID: 41fe728ff7fb
Revises: f1070b63a1c3
Create Date: 2026-03-16 11:08:42.625573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fe728ff7fb'
down_revision = 'f1070b63a1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quality', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('quality')
        batch_op.drop_column('color')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
